name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [18, 19, 20, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main"
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main"
        # Workaround for issue https://github.com/llvm/llvm-project/issues/133861
        sudo ln -s /usr/lib/llvm-${{ matrix.version }}/lib /usr/lib/lib
        sudo ln -s /usr/lib/llvm-${{ matrix.version }}/include /usr/lib/include
        sudo apt-get update
        sudo apt-get install ninja-build clang-${{ matrix.version }} llvm-${{ matrix.version }}-dev libclang-${{ matrix.version }}-dev

    - name: Build clang-i18n
      run: |
        mkdir build && cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. -DLLVM_DIR=/usr/lib/llvm-${{ matrix.version }}/lib/cmake/llvm -DClang_DIR=/usr/lib/llvm-${{ matrix.version }}/lib/cmake/clang
        cmake --build . -j

    - name: Append clang version to clang-i18n artifacts
      id: append_clang_version
      run: |
        cd build
        clang_version=$(clang-${{ matrix.version }} --version | grep -oP 'version \K[0-9.]+' --color=never | tr -d '\n')
        echo "Clang version: $clang_version"
        mkdir -p artifacts
        cp libclang-i18n.so artifacts/libclang-i18n.so.$clang_version
        cp libllvm-i18n.so artifacts/libllvm-i18n.so.$clang_version
        echo "clang_version=$clang_version" >> "$GITHUB_OUTPUT"

    - name: Upload artifacts
      id: artifacts
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        path: build/artifacts
        name: artifacts-${{ github.run_id }}-${{ matrix.version }}
        retention-days: 7
