name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 19, 20, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main"
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main"
        sudo apt-get update
        sudo apt-get install ninja-build llvm-${{ matrix.version }}-dev libclang-${{ matrix.version }}-dev

    - name: Build clang-i18n
      run: |
        mkdir build && cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. -DLLVM_DIR=/usr/lib/llvm-${{ matrix.version }}/lib/cmake/llvm -DClang_DIR=/usr/lib/llvm-${{ matrix.version }}/lib/cmake/clang
        cmake --build . -j
