name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: dtcxzyw/clang-i18n/.github/workflows/build.yml@main

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        pattern: artifacts-${{ github.run_id }}-*
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -R artifacts

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/lib*
